// Trạng thái request trả hàng/hoàn tiền mô phỏng, độc lập với payment status của order.
export enum OrderReturnStatus {
  REQUESTED = "REQUESTED",
  CUSTOMER_CANCELLED = "CUSTOMER_CANCELLED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  AWAITING_SHIPMENT = "AWAITING_SHIPMENT",
  IN_TRANSIT = "IN_TRANSIT",
  SHIPMENT_FAILED = "SHIPMENT_FAILED",
  RECEIVED = "RECEIVED",
  INSPECTION_FAILED = "INSPECTION_FAILED",
  REFUND_PENDING = "REFUND_PENDING",
}
